'use strict';
const $ = id => document.getElementById(id);
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const fresh = () => ({id:null,date:today(),memo:'',photo:null,x:50,y:50});
let state = {version:1,logs:[],slots:Array(20).fill(null),cal:{x:0,y:0,scale:100},draft:fresh()};
let db, photo = null, fits = true, selectedSlot = 0, saveTimer, noticeTimer, queue = Promise.resolve(), photoTicket = 0, loadingPhoto = false;
function notify(message){ $('toast').textContent=message; $('toast').hidden=false; clearTimeout(noticeTimer); noticeTimer=setTimeout(()=>$('toast').hidden=true,4500); }
async function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('sou-making-notes',1); r.onupgradeneeded=()=>r.result.createObjectStore('data'); r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function readDB(){return new Promise((resolve,reject)=>{const r=db.transaction('data').objectStore('data').get('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function persist(){clearTimeout(saveTimer); const snapshot=structuredClone(state); queue=queue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{if(!db){reject(new Error('storage'));return;} const tx=db.transaction('data','readwrite');tx.objectStore('data').put(snapshot,'state');tx.oncomplete=()=>{$('storageStatus').textContent='この端末に保存済み · 写真を外部へ送信しません';resolve(true);};tx.onerror=tx.onabort=()=>reject(tx.error);})).catch(()=>{$('storageStatus').textContent='端末に保存できません。バックアップを保存してください。';return false;});return queue;}
function scheduleSave(){clearTimeout(saveTimer);$('storageStatus').textContent='保存中…';saveTimer=setTimeout(persist,350);}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src;});}
function wrap(ctx,text,width){const lines=[];for(const para of text.split('\n')){let line='';for(const c of Array.from(para)){if(line && ctx.measureText(line+c).width>width){lines.push(line);line='';}line+=c;}lines.push(line);}return lines;}
function renderSticker(canvas,record,im){const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,800,800);let top=98;
 if(im){let sw=im.width,sh=im.height;if(sw/sh>1.5)sw=sh*1.5;else sh=sw/1.5;ctx.drawImage(im,(im.width-sw)*record.x/100,(im.height-sh)*record.y/100,sw,sh,48,48,704,469.333);top=563;}
 ctx.fillStyle='#26352e';ctx.font='38px sans-serif';ctx.textBaseline='top';const lines=wrap(ctx,record.memo,704);const max=im?3:12;lines.slice(0,max).forEach((line,i)=>ctx.fillText(line,48,top+i*46));ctx.fillStyle='#667267';ctx.font='26px sans-serif';ctx.fillText(record.date.replaceAll('-',' / '),48,733);return lines.length<=max;
}
function updatePreview(){fits=renderSticker($('sticker'),state.draft,photo)&&state.draft.memo.length<=80;$('fitWarning').hidden=fits;$('charCount').textContent=`${state.draft.memo.length} / 80`;$('photoControls').hidden=!photo;const enabled=Boolean(photo||state.draft.memo.trim())&&fits&&Boolean(state.draft.date)&&!loadingPhoto;$('save').disabled=!enabled;$('saveSticker').disabled=!enabled;}
async function syncDraft(){const ticket=++photoTicket;photo=null;loadingPhoto=Boolean(state.draft.photo);$('date').value=state.draft.date;$('memo').value=state.draft.memo;$('cropX').value=state.draft.x;$('cropY').value=state.draft.y;$('editorTitle').textContent=state.draft.id?'記録を編集':'今日のひとコマ';updatePreview();if(state.draft.photo){try{const im=await loadImage(state.draft.photo);if(ticket!==photoTicket)return;photo=im;}catch{notify('写真を読み込めませんでした。選び直してください。');}}loadingPhoto=false;updatePreview();}
function showView(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('[data-view]').forEach(el=>{if(el.dataset.view===name)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});if(name==='logs')renderLogs();if(name==='print')renderSheet();window.scrollTo({top:0,behavior:'smooth'});}
function element(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;}
function button(text,fn,cls){const el=element('button',cls,text);el.onclick=fn;return el;}
function updateCounts(){$('logCount').textContent=state.logs.length;$('sheetCount').textContent=state.slots.filter(Boolean).length;$('capacity').textContent=`${state.slots.filter(Boolean).length} / 20 枚`;}
function addToSheet(id){const i=state.slots.indexOf(null);if(i<0){notify('20面が埋まっています。配置を外してから追加してください。');return false;}state.slots[i]=id;return true;}
async function commit(toSheet){if(!fits||loadingPhoto||!$('date').checkValidity()||(!photo&&!state.draft.memo.trim()))return;const rec={...state.draft,id:state.draft.id||crypto.randomUUID(),sticker:$('sticker').toDataURL('image/png')};const index=state.logs.findIndex(l=>l.id===rec.id);if(index<0)state.logs.unshift(rec);else state.logs[index]=rec;const added=toSheet&&addToSheet(rec.id);state.draft=fresh();await syncDraft();const saved=await persist();updateCounts();if(toSheet)showView('print');else showView('logs');notify(saved?(added?'ログを保存して、シールに追加しました':'ログを保存しました'):'保存できませんでした。ログからバックアップを保存してください。');}
function renderLogs(){const root=$('logList');root.replaceChildren();updateCounts();if(!state.logs.length){const box=element('div','empty');box.append(element('h3','','まだ、まっさらなノート。'),element('p','','写真やひと言から、最初の記録を残しましょう。'),button('＋ 記録する',()=>showView('create'),'primary'));root.append(box);return;}for(const rec of state.logs){const card=element('article','log-card'),img=element('img'),content=element('div','log-content'),actions=element('div','log-actions');img.src=rec.sticker;img.alt='保存したシール';const time=element('time','',rec.date);time.dateTime=rec.date;content.append(time,element('p','',rec.memo||'写真の記録'));actions.append(button('シールに追加',async()=>{if(addToSheet(rec.id)){await persist();updateCounts();notify('シールに追加しました');}},'secondary'),button('編集',async()=>{if((state.draft.memo||state.draft.photo)&&!confirm('編集中の下書きを置き換えますか？'))return;state.draft={...rec};delete state.draft.sticker;await syncDraft();scheduleSave();showView('create');}),button('画像保存',()=>download(rec.sticker,`SOU_${rec.date}_${rec.id.slice(0,8)}.png`)),button('削除',async()=>{if(!confirm('このログを削除しますか？シールの配置からも外れます。'))return;state.logs=state.logs.filter(l=>l.id!==rec.id);state.slots=state.slots.map(id=>id===rec.id?null:id);if(state.draft.id===rec.id){state.draft=fresh();await syncDraft();}await persist();renderLogs();}));content.append(actions);card.append(img,content);root.append(card);}}
function geometry(index){const s=state.cal.scale/100;return {left:5+state.cal.x+index%4*50*s,top:23.5+state.cal.y+Math.floor(index/4)*50*s,size:50*s};}
function validBounds(){if(['offsetX','offsetY','scale'].some(id=>!$(id).checkValidity()||$(id).value===''))return false;const first=geometry(0),last=geometry(19);return first.left>=0&&first.top>=0&&last.left+last.size<=210&&last.top+last.size<=297;}
function renderSheet(){const root=$('paper');root.replaceChildren();for(let i=0;i<20;i++){const b=button('',()=>openSlot(i),'slot'),g=geometry(i),rec=state.logs.find(l=>l.id===state.slots[i]);b.style.cssText=`left:${g.left/210*100}%;top:${g.top/297*100}%;width:${g.size/210*100}%;height:${g.size/297*100}%`;b.setAttribute('aria-label',`${i+1}番のマス${rec?'：'+(rec.memo||rec.date):'：空き'}`);if(rec){const im=element('img');im.src=rec.sticker;im.alt='';b.append(im);}else b.append(element('span','','＋'));b.append(element('span','number',i+1));root.append(b);}updateCounts();$('boundsError').hidden=validBounds();$('printButton').disabled=!validBounds()||!state.slots.some(Boolean);$('testPrint').disabled=!validBounds();}
function openSlot(i){selectedSlot=i;$('slotTitle').textContent=`${i+1}番のマスに配置`;$('slotChoices').replaceChildren();if(!state.logs.length)$('slotChoices').append(element('p','hint','「記録する」から先にログを保存してください。'));for(const rec of state.logs){const b=button('',async()=>{state.slots[selectedSlot]=rec.id;$('slotDialog').close();renderSheet();await persist();});const im=element('img');im.src=rec.sticker;im.alt=rec.memo||'写真の記録';b.append(im,element('span','',rec.date));$('slotChoices').append(b);}$('slotDialog').showModal();}
let printMode = false;
function preparePrint(test){const root=$('printRoot');root.replaceChildren();for(let i=0;i<20;i++){const rec=state.logs.find(l=>l.id===state.slots[i]);if(!test&&!rec)continue;const g=geometry(i),el=element(test?'div':'img',test?'print-cell test-cell':'print-cell');el.style.cssText=`left:${g.left}mm;top:${g.top}mm;width:${g.size}mm;height:${g.size}mm`;if(test)el.textContent=`${i+1} / ${g.size.toFixed(2)} mm`;else{el.src=rec.sticker;el.alt='';}root.append(el);}if(test)root.append(element('div','test-caption',`SOU 位置確認｜基準50mm × 50mm｜X ${state.cal.x}mm / Y ${state.cal.y}mm / ${state.cal.scale}%`));}
async function printSheet(test){if(!validBounds())return;printMode=test;preparePrint(test);await Promise.all([...$('printRoot').querySelectorAll('img')].map(im=>im.decode()));await document.fonts.ready;window.print();}
window.addEventListener('beforeprint',()=>preparePrint(printMode));window.addEventListener('afterprint',()=>{printMode=false;});
function download(url,name){const a=element('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();}
function exportBackup(){const blob=new Blob([JSON.stringify(state)],{type:'application/json'}),url=URL.createObjectURL(blob);download(url,`SOU_backup_${today()}.json`);setTimeout(()=>URL.revokeObjectURL(url),10000);}
function validRecord(r){return r&&typeof r.memo==='string'&&r.memo.length<=80&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&Number.isFinite(r.x)&&r.x>=0&&r.x<=100&&Number.isFinite(r.y)&&r.y>=0&&r.y<=100&&(r.photo===null||/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(r.photo));}
function validateState(s){if(!s||s.version!==1||!Array.isArray(s.logs)||!Array.isArray(s.slots)||s.slots.length!==20||!validRecord({...s.draft,date:s.draft?.date||today()})||!s.cal)throw Error('format');const ids=new Set();for(const l of s.logs){if(!validRecord(l)||typeof l.id!=='string'||ids.has(l.id)||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(l.sticker))throw Error('record');ids.add(l.id);}if(s.slots.some(id=>id!==null&&!ids.has(id)))throw Error('slot');if(![s.cal.x,s.cal.y,s.cal.scale].every(Number.isFinite)||Math.abs(s.cal.x)>5||Math.abs(s.cal.y)>20||s.cal.scale<98||s.cal.scale>102)throw Error('calibration');return s;}
async function importPhoto(file){if(!file)return;const ticket=++photoTicket;loadingPhoto=true;updatePreview();let url;try{if(file.size>35*1024*1024)throw Error('size');url=URL.createObjectURL(file);const im=await loadImage(url),c=element('canvas');const s=Math.min(1,1600/Math.max(im.width,im.height));c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const src=c.toDataURL('image/jpeg',.9);const compressed=await loadImage(src);if(ticket!==photoTicket)return;state.draft.photo=src;state.draft.x=50;state.draft.y=50;photo=compressed;$('cropX').value=50;$('cropY').value=50;scheduleSave();}catch{notify('写真を読み込めません。35MB以下のJPEG・PNGなどを選んでください。');}finally{if(url)URL.revokeObjectURL(url);if(ticket===photoTicket){loadingPhoto=false;updatePreview();}}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('camera').onclick=()=>$('cameraInput').click();$('choosePhoto').onclick=()=>$('photoInput').click();for(const id of ['cameraInput','photoInput'])$(id).onchange=e=>{importPhoto(e.target.files[0]);e.target.value='';};
for(const [id,key] of [['memo','memo'],['date','date'],['cropX','x'],['cropY','y']])$(id).oninput=()=>{if(key==='memo'&&$(id).value.length>80)$(id).value=$(id).value.slice(0,80);state.draft[key]=(key==='x'||key==='y')?Number($(id).value):$(id).value;updatePreview();scheduleSave();};
$('removePhoto').onclick=()=>{++photoTicket;loadingPhoto=false;state.draft.photo=null;photo=null;updatePreview();scheduleSave();};
$('save').onclick=()=>commit(false);$('saveSticker').onclick=()=>commit(true);$('newLog').onclick=()=>showView('create');$('resetDraft').onclick=async()=>{if((state.draft.photo||state.draft.memo)&&!confirm('下書きを消して、新しく記録しますか？'))return;state.draft=fresh();await syncDraft();scheduleSave();};
$('closeDialog').onclick=()=>$('slotDialog').close();$('emptySlot').onclick=async()=>{state.slots[selectedSlot]=null;$('slotDialog').close();renderSheet();await persist();};$('clearSheet').onclick=async()=>{if(!state.slots.some(Boolean)||!confirm('シールの配置をすべて外しますか？保存したログは残ります。'))return;state.slots.fill(null);renderSheet();await persist();};
for(const [id,key] of [['offsetX','x'],['offsetY','y'],['scale','scale']])$(id).oninput=()=>{if(!$(id).checkValidity()||$(id).value===''){ $('printButton').disabled=true;$('testPrint').disabled=true;return;}state.cal[key]=Number($(id).value);renderSheet();scheduleSave();};
function syncCalibration(){$('offsetX').value=state.cal.x;$('offsetY').value=state.cal.y;$('scale').value=state.cal.scale;}
$('resetCalibration').onclick=()=>{state.cal={x:0,y:0,scale:100};syncCalibration();renderSheet();scheduleSave();};$('printButton').onclick=()=>printSheet(false).catch(()=>notify('印刷の準備に失敗しました。もう一度お試しください。'));$('testPrint').onclick=()=>printSheet(true).catch(()=>notify('印刷を開始できませんでした。'));$('backup').onclick=exportBackup;$('restore').onclick=()=>$('restoreInput').click();
$('restoreInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>150*1024*1024)throw Error('size');const incoming=validateState(JSON.parse(await file.text()));if(!confirm(`${incoming.logs.length}件のログを復元します。現在のログ・下書き・配置を置き換えます。続けますか？`))return;state=incoming;await syncDraft();syncCalibration();const ok=await persist();renderLogs();renderSheet();notify(ok?'バックアップを復元しました':'復元しましたが端末に保存できません。');}catch{notify('このバックアップは読み込めません。SOUで保存したJSONを選んでください。');}};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')persist();});
(async()=>{try{db=await openDB();const saved=await readDB();if(saved)state=validateState(saved);$('storageStatus').textContent='この端末に保存します · 写真を外部へ送信しません';}catch{db=undefined;$('storageStatus').textContent='保存データを開けません。バックアップで記録を持ち出してください。';}await syncDraft();syncCalibration();renderLogs();renderSheet();})();
